
default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: messykitchenstories_development


test:
  <<: *default
  database: messykitchenstories_test


production:
  <<: *default
  database: messykitchenstories_production
  username: messykitchenstories
  password: <%= ENV['MESSYKITCHENSTORIES_DATABASE_PASSWORD'] %>
